### ISSUE TITLE
Darshil_theCoder

### ISSUE THREAD

**Issue by darshil-thecoder** [Hack-Club-SVIT/HacktoberFest-2021#22]
FEEDBACK:
It was a very interesting as well as very interactive session conducted by Siddharth Dayalwal , he gave a brief introduction about the HACK THIS FALL , what is Hackathons , tells us about what is open source then what is git and github and clear all the doubts which was there in mind before the session . Atlast I just to want say that it was a extremely wonderful session. 

Even the hands on practice given by the AAYAN was also wonderful , he is also a great inspiration for all of us .

SUGGESTION:
I want to understand about the DSA with hands on practice . I mean making anything using the DSA.
Thank you .

**Comment by imjp19** [comment]
Thank you for your feedback and suggestion. We will think about it :)
